
$(function() {

    // Populate using an object literal

    WTF.init({

        heading: [
            "Congrats fuckheads, you just woke up the",
            "Do my fucking eyes deceive me or is that the",
            "Fuck, we just pissed off the",
            "I can't fucking believe it, there's that",
            "Legends speak of this fucking",
            "Holy fucking shit, is that the",
            "Roll fucking initiative, here comes the",
            "Those dumbass villagers never told us about the",
            "Whose bright idea was it to provoke the",
            "You dipshits somehow managed to piss off the"
        ],
        response: [
            "Already fucking killed it",
            "Give me a challenging one next time",
            "Hit me with another one",
            "That one sucks, give me another one",
            "That one's fucking dumb",
            "That's not what it fucking is"
        ],
        template: [
            "@adjective @creature that @uniqueTrait",
            "@adjective, @adjective @creature that @uniqueTrait",
            "@adjective @creature from @location that @uniqueTrait"
        ],
        adjective: [
            "abyssal",
            "affectionate",
            "ancient",
            "angsty",
            "apathetic",
            "blind",
            "colorful",
            "confused",
            "curious",
            "creepy",
            "deaf",
            "elderly",
            "evil",
            "fast",
            "feathered",
            "firebreathing",
            "flying",
            "foul-smelling",
            "furry",
            "elusive",
            "evasive",
            "giant",
            "gigantic",
            "good-looking",
            "greasy",
            "hairy",
            "hardworking",
            "huge-ass",
            "infamous",
            "infernal",
            "invisible",
            "kindly",
            "larger-than-average",
            "lazy",
            "lonely",
            "lovecraftian",
            "magical",
            "middle-aged",
            "nervous",
            "one-eyed",
            "one-legged",
            "passive-aggressive",
            "pissed-off",
            "poisonous",
            "revered",
            "scarred",
            "self-righteous",
            "shy",
            "sleepy",
            "slow",
            "smooth-talking",
            "sneaky",
            "teenaged",
            "tiny",
            "undead",
            "up-and-coming",
            "vicious",
            "winged",
            "zealous"
        ],
        creature: [
            "air elemental",
            "archmage",
            "artificer",
            "assassin",
            "awakened tree",
            "gang of bandits",
            "bard",
            "basilisk",
            "beholder",
            "bugbear",
            "centaur",
            "chimera",
            "COCKatrice",
            "cow",
            "cyclops",
            "death knight",
            "death tyrant",
            "demon",
            "devil",
            "direwolf",
            "djinni",
            "black dragon",
            "blue dragon",
            "green dragon",
            "red dragon",
            "white dragon",
            "drow",
            "druid",
            "earth elemental",
            "fflumph",
            "fire elemental",
            "flail snail",
            "flameskull",
            "froghemoth",
            "ghost",
            "ghoul",
            "cloud giant",
            "fire giant",
            "frost giant",
            "stone giant",
            "githyanki",
            "githzerai",
            "gladiator",
            "goblin",
            "gorgon",
            "griffon",
            "harpy",
            "hell hound",
            "hobgoblin",
            "hydra",
            "incubus",
            "kenku",
            "knight",
            "kobold",
            "lich",
            "manticore",
            "mind flayer",
            "minotaur",
            "mummy",
            "ogre",
            "orc warband",
            "owlbear",
            "purple worm",
            "roc",
            "skeleton",
            "sorcerer",
            "succubus",
            "tarrasque",
            "troll",
            "vampire",
            "warlock",
            "warlord",
            "water elemental",
            "werewolf",
            "wight",
            "conjurer",
            "diviner",
            "enchanter",
            "evoker",
            "illusionist",
            "necromancer",
            "wraith",
            "wyvern",
            "yeti",
            "yugoloth",
            "zombie"
        ],
        location: [
            "a cave beneath the mountains",
            "a cursed kingdom",
            "a dimension of madness",
            "a floating citadel",
            "a haunted mansion",
            "a gloomy dungeon",
            "a massive labyrinth",
            "a realm of eternal darkness",
            "a wizard's lair",
            "an abandoned temple",
            "an ancient forest",
            "another plane of existence",
            "deep underground",
            "the abyss",
            "the deepest jungle",
            "the forbidden castle",
            "the icy tundra",
            "the nine hells",
            "the swamps of despair"
        ],
        uniqueTrait: [
            "cannot be killed by mortals",
            "captures children",
            "comes from another dimension",
            "destroys villages just for fun",
            "guards an ancient treasure",
            "has a tragic backstory",
            "hates dwarves",
            "hates elves",
            "hates gnomes",
            "hates halflings",
            "hates humans",
            "hates orcs",
            "hates tieflings",
            "hates music",
            "is actually pretty chill",
            "is defending its young",
            "is going through some personal issues",
            "is searching for its family",
            "is searching for the chosen one",
            "is immune to fire",
            "is immune to magic",
            "is vulnerable to magic",
            "just wants a friend",
            "just wants to be left alone",
            "just wants to dance",
            "just wants to talk to someone",
            "killed your family",
            "killed your friend",
            "loves music",
            "loves murder",
            "loves treasure",
            "majored in theater",
            "revels in bloodshed",
            "spits poison",
            "started a death cult",
            "was exiled from its home",
            "was created by an eldritch god",
            "was cursed by an evil wizard"
        ]
    });

    // Populate using a JSON file
    // WTF.init( 'sample.json' );

    // Populate using a Google spreadsheet ID (you must publish it first!)
    // @see https://support.google.com/drive/answer/37579?hl=en
    //WTF.init( '0AvG1Hx204EyydF9ub1M2cVJ3Z1VGdDhTSWg0ZV9LNGc' );

});
